name: super_quest
description: A new Flutter project.
version: 0.0.0
publish_to: none

environment:
  sdk: ^2.18.5
  flutter: ^3.3.9

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.5.0

flutter:
  assets:
    - assets/images/