name: super_quest
description: A new Flutter project.
version: 0.0.0
publish_to: none

environment:
  sdk: ^2.18.4
  flutter: ^3.3.10

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.5.0
  flame_audio: ^1.3.3
  flame_tiled: ^1.4.0
  flame_forge2d: ^0.12.2
  flutter_carousel_slider: 1.1.0

flutter:
  assets:
    - assets/images/
    - assets/music/
    - assets/audio/fundo.mp3